# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180812_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='api.Recipe'),
        ),
    ]
